Importing the Dependencies

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, classification_report

In [2]:
# loading the dataset to a Pandas DataFrame
credit_card_data = pd.read_csv("C:\\Users\\Asus\\Downloads\\End2End project\\Credit_Card_Fraud_Detection\\archive\\creditcard.csv")

In [3]:
# first 5 rows of the dataset
credit_card_data.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
credit_card_data.tail()

Time         V1         V2        V3        V4        V5  \
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[5 rows x 31 columns]

In [5]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

In [6]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [7]:
# distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

This Dataset is highly unblanced

0 --> Normal Transaction

1 --> fraudulent transaction

In [8]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [9]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)


In [10]:
# statistical measures of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [11]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [12]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

Time        V1        V2        V3        V4        V5  \
Class                                                                   
0      94838.202258  0.008258 -0.006271  0.012171 -0.007860  0.005453   
1      80746.806911 -4.771948  3.623778 -7.033281  4.542029 -3.151225   

             V6        V7        V8        V9  ...       V20       V21  \
Class                                          ...                       
0      0.002419  0.009637 -0.000987  0.004467  ... -0.000644 -0.001235   
1     -1.397737 -5.568731  0.570636 -2.581123  ...  0.372319  0.713588   

            V22       V23       V24       V25       V26       V27       V28  \
Class                                                                         
0     -0.000024  0.000070  0.000182 -0.000072 -0.000089 -0.000295 -0.000131   
1      0.014049 -0.040308 -0.105130  0.041449  0.051648  0.170575  0.075667   

           Amount  
Class              
0       88.291022  
1      122.211321  

[2 rows x 30 columns]

Under-Sampling

Build a sample dataset containing similar distribution of normal transactions and Fraudulent Transactions

Number of Fraudulent Transactions --> 492

In [13]:
legit_sample = legit.sample(n=492)

Concatenating two DataFrames

In [14]:
# defined new dataset with 492 fraud and 492 (random) legit data points
new_dataset = pd.concat([legit_sample, fraud], axis=0) # axis = 0 means row-wise operation, 1 means column-wise operation

In [15]:
new_dataset.head()

Time        V1        V2        V3        V4        V5        V6  \
204643  135375.0  1.748844 -1.109410 -0.493947  0.644342 -0.928307 -0.021360   
39355    39802.0  0.903131 -1.061429  0.602521  0.091102 -1.032249  0.430731   
8504     11410.0  1.319184  0.289548  0.151244  0.135937 -0.232637 -1.266993   
158533  111413.0 -1.265541  1.005069  0.368255  4.654873  1.279950  0.439903   
218805  141465.0  0.208744 -1.029454  1.211577 -2.587052 -1.229665  0.068832   

              V7        V8        V9  ...       V21       V22       V23  \
204643 -0.641387 -0.026709 -0.260653  ... -0.384878 -0.971232  0.319314   
39355  -0.645674  0.288977  1.195631  ... -0.151458 -0.654407 -0.164995   
8504    0.214054 -0.461028  1.230655  ... -0.225204 -0.336526 -0.028697   
158533 -0.011064  0.339098 -1.240034  ...  0.217695  0.996725  0.294633   
218805 -1.026706  0.241571 -1.363648  ...  0.068660  0.615029  0.259773   

             V24       V25       V26       V27       V28  Amount  Class  
204643  0.600581 -0.532092 -0.973134  0.046004  0.017959  178.00      0  
39355  -0.452740  0.107436  0.963480 -0.079246  0.021771  175.40      0  
8504    0.433335  0.428586  0.999223 -0.125184 -0.009326    5.99      0  
158533  0.739095 -0.506331  0.409072 -0.043285  0.023330    9.30      0  
218805 -0.458187 -1.643682 -0.463289  0.326544  0.278681   32.85      0  

[5 rows x 31 columns]

In [16]:
new_dataset.tail()

Time        V1        V2        V3        V4        V5        V6  \
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494   
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536   
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346   
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548   
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695   

              V7        V8        V9  ...       V21       V22       V23  \
279863 -0.882850  0.697211 -2.064945  ...  0.778584 -0.319189  0.639419   
280143 -1.413170  0.248525 -1.127396  ...  0.370612  0.028234 -0.145640   
280149 -2.234739  1.210158 -0.652250  ...  0.751826  0.834108  0.190944   
281144 -2.208002  1.058733 -1.632333  ...  0.583276 -0.269209 -0.456108   
281674  0.223050 -0.068384  0.577829  ... -0.164350 -0.295135 -0.072173   

             V24       V25       V26       V27       V28  Amount  Class  
279863 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00      1  
280143 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76      1  
280149  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89      1  
281144 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00      1  
281674 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53      1  

[5 rows x 31 columns]

In [17]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [18]:
new_dataset.groupby('Class').mean()

Time        V1        V2        V3        V4        V5  \
Class                                                                   
0      94953.699187  0.180855  0.040706 -0.081172  0.007396 -0.006330   
1      80746.806911 -4.771948  3.623778 -7.033281  4.542029 -3.151225   

             V6        V7        V8        V9  ...       V20       V21  \
Class                                          ...                       
0     -0.045063  0.017965  0.028546 -0.060326  ...  0.030884  0.025824   
1     -1.397737 -5.568731  0.570636 -2.581123  ...  0.372319  0.713588   

            V22       V23       V24       V25       V26       V27       V28  \
Class                                                                         
0      0.034637 -0.033832 -0.008213  0.020321  0.013612 -0.022463 -0.003126   
1      0.014049 -0.040308 -0.105130  0.041449  0.051648  0.170575  0.075667   

           Amount  
Class              
0       87.935488  
1      122.211321  

[2 rows x 30 columns]

Splitting the data into Features & Targets

In [19]:
X = new_dataset.drop(columns='Class', axis=1) # dropped the 'Class' Column from the dataset
Y = new_dataset['Class']

In [20]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
204643  135375.0  1.748844 -1.109410 -0.493947  0.644342 -0.928307 -0.021360   
39355    39802.0  0.903131 -1.061429  0.602521  0.091102 -1.032249  0.430731   
8504     11410.0  1.319184  0.289548  0.151244  0.135937 -0.232637 -1.266993   
158533  111413.0 -1.265541  1.005069  0.368255  4.654873  1.279950  0.439903   
218805  141465.0  0.208744 -1.029454  1.211577 -2.587052 -1.229665  0.068832   
...          ...       ...       ...       ...       ...       ...       ...   
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494   
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536   
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346   
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548   
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695   

              V7        V8        V9  .

In [22]:
print(Y)  # 0 is Normal, 1 is Fraudulent

204643    0
39355     0
8504      0
158533    0
218805    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64


Split the data into Training data & Testing Data

In [23]:
'''Generally this splitting method is used in Supervised ML, where we know the labelled Y-data (true values we want in predictions)
For accuracy, we match the predited values with these Y labels both in train as well as test datapoints'''
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [25]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)


Model Training

Logistic Regression

In [26]:
model = LogisticRegression()

In [27]:
# training the Logistic Regression Model with Training Data
model.fit(X_train, Y_train)

C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

Model Evaluation

Accuracy Score

In [28]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [29]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9440914866581956


In [30]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [31]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9289340101522843


Evaluate precision, recall and F1-score: critical metrics in fraud detection.
- Precision reflects the proportion of detected frauds that are true frauds, i.e. “When the model says Positive, how often is it correct?”
- Recall reflects the proportion of actual frauds detected, i.e. “Out of all actual Positives, how many did the model find?”
- F1-score balances both: It is a way to measure a model’s performance by combining precision and recall into a single number.


In [32]:
precision_train = precision_score(Y_train, X_train_prediction)
recall_train = recall_score(Y_train, X_train_prediction)

precision_test = precision_score(Y_test, X_test_prediction)
recall_test = recall_score(Y_test, X_test_prediction)

print(f"Precision_test: {precision_test:.3f} ({precision_test*100:.1f}%)")
print(f"Recall_test:    {recall_test:.3f} ({recall_test*100:.1f}%)")

print(f"Precision_train: {precision_train:.3f} ({precision_train*100:.1f}%)")
print(f"Recall_train:    {recall_train:.3f} ({recall_train*100:.1f}%)")

print("\nTest-Classification Report:")
print(classification_report(Y_test, X_test_prediction, target_names=['Normal', 'Fraud']))

print("\nTrain-Classification Report:")
print(classification_report(Y_train, X_train_prediction, target_names=['Normal', 'Fraud']))

print("\nF1-score results:")
f1_score_test = 2 * (precision_test * recall_test) / (precision_test + recall_test)
print(f"F1 Score_test: {f1_score_test:.3f}")
f1_score_train = 2 * (precision_train * recall_train) / (precision_train + recall_train)
print(f"F1 Score_train: {f1_score_train:.3f}")


Precision_test: 0.967 (96.7%)
Recall_test:    0.888 (88.8%)
Precision_train: 0.963 (96.3%)
Recall_train:    0.924 (92.4%)

Test-Classification Report:
              precision    recall  f1-score   support

      Normal       0.90      0.97      0.93        99
       Fraud       0.97      0.89      0.93        98

    accuracy                           0.93       197
   macro avg       0.93      0.93      0.93       197
weighted avg       0.93      0.93      0.93       197


Train-Classification Report:
              precision    recall  f1-score   support

      Normal       0.93      0.96      0.95       393
       Fraud       0.96      0.92      0.94       394

    accuracy                           0.94       787
   macro avg       0.94      0.94      0.94       787
weighted avg       0.94      0.94      0.94       787


F1-score results:
F1 Score_test: 0.926
F1 Score_train: 0.943


FEATURE IMPORTANCE ANALYSIS:
- Analyze feature importance based on logistic regression coefficients.
- Highlights which PCA components are most indicative of fraud.


In [37]:
print("\n" + "="*60)
print("FEATURE IMPORTANCE ANALYSIS")
print("="*60)

feature_names = X.columns
coefficients = model.coef_[0]
feature_importance = pd.DataFrame({
    'Feature': feature_names,
    'Coefficient': coefficients,
    'Abs_Coefficient': np.abs(coefficients),
}).sort_values('Abs_Coefficient', ascending=False).reset_index(drop=True)

print("Top 10 Most Influential Features:")
for i in range(10):
    feature = feature_importance.iloc[i]
    print(f"{i+1:2d}. {feature['Feature']}: {feature['Coefficient']:+.4f}, i.e.{feature['Abs_Coefficient']:+.4f} in absolute")


FEATURE IMPORTANCE ANALYSIS
Top 10 Most Influential Features:
 1. V14: -0.9289, i.e.+0.9289 in absolute
 2. V4: +0.7460, i.e.+0.7460 in absolute
 3. V3: -0.6969, i.e.+0.6969 in absolute
 4. V12: -0.5165, i.e.+0.5165 in absolute
 5. V17: -0.4161, i.e.+0.4161 in absolute
 6. V10: -0.3981, i.e.+0.3981 in absolute
 7. V16: -0.2801, i.e.+0.2801 in absolute
 8. V5: +0.2696, i.e.+0.2696 in absolute
 9. V8: -0.2561, i.e.+0.2561 in absolute
10. V7: -0.2474, i.e.+0.2474 in absolute


PROJECT SUMMARY
- Summary of model performance and evaluation outcomes.
- Includes core metrics relevant to fraud detection effectiveness and business impact.

In [38]:
print("\n" + "="*70)
print("FINAL PROJECT SUMMARY")
print("="*70)

print(f"Dataset size: {credit_card_data.shape[0]:,} transactions")
print(f"Model type: Logistic Regression")
print(f"Accuracy (test data): {test_data_accuracy*100:.1f}%")
print(f"Precision (test data): {precision_test*100:.1f}%")
print(f"Recall (test data): {recall_test*100:.1f}%")
print(f"F1 Score_test: {f1_score_test*100:.1f}%")

print("\nProject execution completed.")



FINAL PROJECT SUMMARY
Dataset size: 284,807 transactions
Model type: Logistic Regression
Accuracy (test data): 92.9%
Precision (test data): 96.7%
Recall (test data): 88.8%
F1 Score_test: 92.6%

Project execution completed.


* Accuracy (92.9%) is high, showing the model correctly classifies most transactions.

* Precision (96.7%) means when the model flags a transaction as fraud, it is correct about 97% of the time. This is excellent to minimize false alarms that annoy customers or waste resources.

* Recall (88.8%) indicates the model correctly detects nearly 89% of all actual fraud cases, which is very good to reduce financial losses.

* F1 Score (92.6%) balances precision and recall, showing the model performs well overall in identifying fraud without too many false positives or missed cases.

* Using 30 PCA-transformed features is typical to reduce dimensionality while preserving important patterns.

Based on the dataset:

* Total transactions: 284,807

* Fraud transactions: 492

* Average fraud amount: $122.21

* Average legitimate transaction amount: $88.29

Calculated totals:

* Total fraud amount: approximately $60,127

* Total legit amount: approximately $25,102,171

* Overall transaction amount: approximately $25,162,298

In [45]:
print("Detecting 88.8% of the fraud cases potentially prevents \naround $53,393 i.e. 88.8% of total fraud transactions = $60,127 in fraudulent losses in the dataset period.")

Detecting 88.8% of the fraud cases potentially prevents 
around $53,393 i.e. 88.8% of total fraud transactions = $60,127 in fraudulent losses in the dataset period.
